pahchina/apps/patient/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = 'zhwei'

from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('',

    url(r'^profile/$', views.Profile.as_view(), name='profile-patient'),

    url(r'^profile/update/$', views.UpdateProfile.as_view(), name='update-patient-profile'),


    #url(r'^admin/list/$', views.ListPatient.as_view(), name='admin-list-patient'),
    #url(r'^admin/detail/(?P<pk>\d+)/$', views.DetailPatient.as_view(), name='admin-detail-patient'),
    #url(r'^admin/update/(?P<pk>\d+)/$', views.UpdatePatient.as_view(), name='admin-update-patient'),
    #

    #url(r'^admin/dosage/detail/patient/(?P<pk>\d+)/$', views.DeleteDrug.as_view(),
    #    name='admin-detail-patient-dosage'),

    url(r'^dosage/detail/$', views.DetailOwnDosage.as_view(), name='detail-dosage'),
    url(r'^dosage/create/$', views.CreateOwnDosage.as_view(), name='create-dosage'),

    url(r'^admin/dosage/list/$', views.ListDosage.as_view(), name='admin-list-dosage'),
    url(r'^admin/dosage/detail/(?P<pk>\d+)/$', views.DetailPatientDosage.as_view(),
        name='admin-detail-patient-dosage'),

    url(r'^admin/dosage/create/(?P<pk>\d+)/$', views.CreateDosage.as_view(), name='admin-create-dosage'),
    url(r'^admin/dosage/update/(?P<pk>\d+)/$', views.UpdateDosage.as_view(), name='admin-update-dosage'),

)

pahchina/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# 同步创建相关身份
# from .apps.utils import OnCreate

from .apps.index import views


urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^i/', include('pahchina.apps.index.urls')),
    url(r'^about/$', views.About.as_view(), name='about'),

    # apps
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),

    # include accounts
    url(r'^accounts/', include('pahchina.apps.accounts.urls')),
    url(r'^patients/', include('pahchina.apps.patient.urls')),
    url(r'^activity/', include('pahchina.apps.activity.urls')),
    url(r'^volunteer/', include('pahchina.apps.volunteer.urls')),
    url(r'^donate/', include('pahchina.apps.donate.urls')),
    url(r'^medical/', include('pahchina.apps.medical.urls')),
    url(r'^site/', include('pahchina.apps.website.urls')),
    url(r'news/', include('pahchina.apps.news.urls')),
    url(r'region/', include('pahchina.apps.region.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pahchina/apps/patient/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse

from ..accounts.models import User
from ..volunteer.models import Volunteer
from ..utils.models import TimeStampedModel
#from ..medical.models import Doctor

SEX_CHOICES=(('1','男'),('0', '女'),('2','隐私'))

class Patient(TimeStampedModel):

    user = models.OneToOneField(User, blank=True)

    medical_history = models.TextField(verbose_name='病史', max_length=200,
                                       help_text='病情描述，叙述患病经过以及治疗和用药状况',
                                       blank=True, null=True)
    # 初诊
    init_diag_hosp = models.CharField(verbose_name='初诊医院名称', max_length=50,
                                      blank=True, null=True)
    init_diag_hosp_type = models.CharField(verbose_name='初诊医院类型', max_length=20,
                                           choices=(
                                               ("sjyy","省级医院"),
                                               ("xsjyy","县市级医院"),
                                               ("sqyy","社区医院"),
                                               ("xzyy","乡镇医院"),
                                               ("ncyy","农村医院"),
                                               ("srzs","私人诊所"),
                                               ("other",""),
                                           ),
                                           blank=True, null=True)
    #init_diag_hosp_type = models.CharField(verbose_name='初诊医院类型', max_length=20,
    #                                       blank=True, null=True)
    init_diag_doct_conclu = models.TextField(verbose_name='初诊医生诊断结论', max_length=500,
                                             blank=True, null=True)
    is_confirm = models.BooleanField(verbose_name='是否确认肺动脉高压',
                                     choices=((False,'否'),(True,'是')),default=False,)
    why_not_confirm = models.CharField(verbose_name='未确诊原因', max_length=10,
                                       choices=(
                                           ("bqbyz","病情不严重"),
                                           ("jjyyzh","经济原因暂缓"),
                                           ("fcwhsyy","附近无合适医院"),
                                           ("other","其他（请注明）"),
                                       ),
                                       blank=True, null=True)
    # 确诊
    confirm_pah_date = models.DateField(verbose_name='确诊PAH日期',
                                        blank=True, null=True)
    confirm_hospital = models.CharField(verbose_name='确诊医院', max_length=20,
                                        blank=True, null=True)
    confirm_section = models.CharField(verbose_name='确诊科室', max_length=20,
                                       blank=True, null=True)
    confirm_doctor = models.CharField(verbose_name='医生', max_length=10,
                                      blank=True, null=True)
    exam_func = models.CharField(verbose_name='检查手段', max_length=20,
                                 choices=(
                                     ("xzcc","心脏彩超"),
                                     ("xdg","心导管"),
                                     ("fdmzy","肺动脉造影"),
                                     ("fzkt","肺阻抗图"),
                                     ("cgz","磁共振"),
                                     ("other","其他（请注明）"),
                                 ),
                                 blank=True, null=True)
    doctor_diagnosis = models.ImageField(verbose_name='医生诊断说明',
                                         help_text='上传诊断书照片，申请资助使用',
                                         upload_to='diagnosis',
                                         blank=True, null=True)
    incidence_reason = models.CharField(verbose_name='发病原因', max_length=100,
                                        choices=(
                                            ("tfx","特发性PAH"),
                                            ("jdzzbhb","结缔组织病合并PAH"),
                                            ("jzx","家族性PAH"),
                                            ("fss","肺栓塞"),
                                            ("xxfqhb","先心房缺合并PAH"),
                                            ("xxsqhb","先心室缺合并PAH"),
                                            ("fzxxhb","复杂先心合并PAH"),
                                            ("xxsh","先心术后PAH"),
                                            ("dmy","动脉炎"),
                                            ("bqc","不清楚病因或尚未明确诊断"),
                                            ("other","其他（请注明）"),
                                        ),
                                   blank=True, null=True)
    # 定期检查
    has_regular_check = models.BooleanField(verbose_name='是否定期检查',
                                            choices=((False,'否'),(True,'是')),default=False)
    regular_check_rate = models.PositiveIntegerField(verbose_name='定期检查频率',
                                                     choices=[(n, n) for n in range(1,13)].append((999,'其他')),
                                                     help_text='几个月进行一次检查',
                                   blank=True, null=True)
    un_regular_check_reason = models.CharField(verbose_name='不定期检查的原因',max_length=20,
                                               choices=(
                                                           ("bgwd","病情稳定"),
                                                           ("tmf","太麻烦"),
                                                           ("bzs","不重视"),
                                                           ("fytg","费用太高"),
                                                           ("ltyy","路途遥远"),
                                                           ("other","其他（请注明）"),
                                                       ),
                                               help_text='可多选',
                                   blank=True, null=True)
    # 日常
    routine_hospital = models.CharField(verbose_name='日常就诊医院', max_length=30,
                                        help_text='居住地附近的医院（外键）',
                                   blank=True, null=True)
    # 随访相关
    follow_up_hospital = models.CharField(verbose_name='随访检查医院', max_length=30,
                                          help_text='十大主要诊疗基地医院（外键）',
                                          blank=True, null=True)
    follow_up_doctor = models.CharField(verbose_name='随访主治医生', max_length=10,
                                        help_text='随访主治医生（外键）',
                                        blank=True, null=True)
    follow_up_target = models.CharField(verbose_name='随访检查目的', max_length=30,
                                        choices=(
                                            ("","波生坦赠药计划"),
                                            ("","安立生坦赠药计划"),
                                            ("","万他维赠药计划"),
                                            ("other","其他（请注明）"),
                                        ),
                                        blank=True, null=True)

    medical_evaluate = models.CharField(verbose_name='对医疗服务评价', max_length=20,
                                        choices=(
                                            ("fcmy","非常满意"),
                                            ("my","满意"),
                                            ("yb","一般"),
                                            ("bmy","不满意"),
                                            ("fcbmy","非常不满意"),
                                        ),
                                        blank=True, null=True)

    # 目前状况

    present_schedule = models.CharField(verbose_name='目前治疗方案', max_length=10,
                                   blank=True, null=True)
    present_schedule_pay = models.CharField(verbose_name='目前治疗方案每月药费', max_length=20,
                                   blank=True, null=True)
    present_drugs = models.CharField(verbose_name='目前用药(外键）', max_length=10,
                                   blank=True, null=True)
    other_drugs = models.CharField(verbose_name='上面没有列出的药物', max_length=30,
                                   blank=True, null=True)

    # 吸氧
    has_daily_oxygen = models.BooleanField(verbose_name='是否每天吸氧治疗',
                                           choices=((False,'否'),(True,'是')),default=False)
    daily_oxygen_hours = models.PositiveIntegerField(verbose_name='每天吸氧时间', help_text='单位：（小时）',
                                                     choices=[(n,n) for n in range(1,25)],
                                                     blank=True, null=True)
    oxygen_way = models.CharField(verbose_name='吸氧方式',max_length=10,
                                  choices=(
                                      ("jyzyj","家用制氧机"),
                                      ("yyzyj","医用制氧机"),
                                      ("yyhsq","医院或者社区医疗室"),
                                  ),
                                  blank=True, null=True)
    oxygenerator = models.CharField(verbose_name='制氧机品牌和型号', max_length=30,
                                    help_text="如：鱼跃 F-3000",
                                    blank=True, null=True)
    oxy_is_recommend = models.BooleanField(verbose_name='是否推荐此品牌',
                                           choices=((False,"不推荐"),(True,"推荐"),))

    # 经济状况
    year_drugs_pay = models.CharField(verbose_name='年药费支出', max_length=20,
                                        help_text="上述日常药物的费用，单位：元",
                                        blank=True, null=True)
    year_medical_pay = models.CharField(verbose_name='年治疗费支出', max_length=30,
                                        help_text='日常药费之外的住院、检查及差旅费',
                                        blank=True, null=True)

    year_pi = models.CharField(verbose_name='个人年收入', max_length=10,
                               blank=True, null=True)
    year_pi_source = models.CharField(verbose_name='个人收入来源', max_length=10,
                                      choices=(

pahchina/apps/patient/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = 'zhwei'

from django import forms
#from django.contrib.localflavor.cn.forms import CNProvinceSelect

from .models import Patient, Dosage
from ..utils.fields import ChoiceWithOtherWidget, ChoiceWithOtherField


class UpdatePatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        exclude = ('user',)


class CreateDosageForm(forms.ModelForm):
    """ 用于患者创建自己的用药状况
    """

    class Meta:
        model = Dosage
        fields = ('drug', 'dose')

    def __init__(self, patient=None, *args, **kwargs):
        super(CreateDosageForm, self).__init__(*args, **kwargs)
        self._patient = patient

    def save(self, commit=True):
        context = super(CreateDosageForm, self).save(commit=False)
        context.patient = self._patient
        context.save()


class AdminCreateDosageForm(forms.ModelForm):
    """ 管理员用来创建患者的用药状况
    """

    class Meta:
        model = Dosage
        fields = ('drug', 'dose')

    def save(self, commit=True):
        super(AdminCreateDosageForm, self).save()

pahchina/apps/patient/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render_to_response as r2r, get_object_or_404

from .models import Patient, Drug, Dosage
import forms
from .forms import UpdatePatientForm, CreateDosageForm, AdminCreateDosageForm
from ..utils import SuperRequiredMixin



class Profile(generic.DetailView):
    """ 患者用来查看个人信息
    """
    template_name = 'profile-patient.html'

    def get_object(self, queryset=None):
        try:
            return self.request.user.patient
        except:
            raise Http404

class UpdateProfile(generic.UpdateView):
    """ 患者更新个人信息
    患者用来更新个人患者基础信息
    """
    form_class = UpdatePatientForm
    success_url = reverse_lazy('profile-patient')
    template_name = 'update-user-profile.html'

    def get_object(self, queryset=None):
        return self.request.user.patient


class ListDosage(SuperRequiredMixin, generic.ListView):
    """ 使用剂量列表
    管理员使用
    用来查看所有患者的用药记录，这里只用时间的先后，不区分患者
    测试功能，后期可能用来统计数据或者其他操作
    """
    model = Dosage
    context_object_name = 'dosage_list'
    template_name = 'list-dosage.html'

class DetailPatientDosage(SuperRequiredMixin, generic.DetailView):
    """ 患者用药详情页面
    管理员用来查看患者在那个时间段用了什么药，药量是多少等
    """
    model = Patient
    context_object_name = 'patient'
    template_name = 'detail-patient-dosage.html'

    def get_context_data(self, **kwargs):
        context = super(DetailPatientDosage, self).get_context_data( **kwargs)
        context['dosage_list'] = Dosage.objects.filter(patient_id = self.kwargs['pk'])
        return context

class DetailOwnDosage(generic.DetailView):
    """ 患者查看个人用药记录
    患者在登录后查看自己的用药记录
    """
    context_object_name = 'dosage_list'
    template_name = 'detail-dosage.html'

    def get_object(self, queryset=None):
        return Dosage.objects.filter(patient=self.request.user.patient)

class CreateOwnDosage(generic.FormView):
    """ 患者创建个人用药记录
    患者在登录后创建自己的用药记录
    """

    form_class = CreateDosageForm
    success_url = reverse_lazy('detail-dosage')
    template_name = 'update-user-profile.html'

    def get_form_kwargs(self):
        kwargs = super(CreateOwnDosage, self).get_form_kwargs()
        kwargs['patient'] = self.request.user.patient
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(CreateOwnDosage, self).form_valid(form)


class CreateDosage(SuperRequiredMixin, generic.FormView):
    """ 管理员创建患者用药记录
    """
    model = Dosage
    form_class = CreateDosageForm
    template_name = 'admin-update.html'

    def get_success_url(self):
        return reverse('admin-detail-patient-dosage', kwargs=self.kwargs)
    
    def get_form_kwargs(self):
        kwargs = super(CreateDosage, self).get_form_kwargs()
        kwargs['patient'] = get_object_or_404(Patient, id=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(CreateDosage, self).form_valid(form)

class UpdateDosage(SuperRequiredMixin, generic.UpdateView):
    """ 管理员修改患者用药记录
    """
    model = Dosage
    success_url = reverse_lazy('admin-list-dosage')
    template_name = 'admin-update.html'

pahchina/apps/patient/templates/confirm_delete.html
{% extends 'base-admin.html' %}

{% block title %}
删除{{ object.verbose_name }} {{ object.name }}
{% endblock %}

{% block content %}

<div class="span7 well">

<h3>删除{{ verbose_name }}</h3>
    <p><strong>注意！</strong></p>

    <p>你确定要删除 {{ object.verbose_name }}&nbsp;
        <span class="badge badge-important">{{ object }}</span>&nbsp;吗?</p>

<form action="" method="post">{% csrf_token %}
    <div>
        <input type="hidden" name="post" value="yes" />
            <br/>
        <a href="#" onclick="location.href=document.referrer;" class="btn btn-primary">不,我返回</a>&nbsp;
        <input type="submit" value="是的,我确定!" class="btn btn-danger"/>
    </div>
</form>
</div>

{% endblock %}

pahchina/apps/patient/templates/detail-dosage.html
{% extends 'index-with-menu.html' %}

{% block title %}用药记录{% endblock %}
{% block h3title %}用药记录{% endblock %}

{% block side-content %}

    <div>
        {% for dosage in dosage_list %}
            <div class="well well-small">
                <p><span class="badge badge-inverse">{{ dosage.datetime|date:'Y年m月d日' }}</span></p>
                <p><span class="label label-info"><i class="icon-plus-sign"></i>&nbsp;{{ dosage.drug }}</span>
                    服药剂量：{{ dosage.dose }}
                </p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

pahchina/apps/patient/templates/detail-patient-dosage.html
{% extends 'base-admin.html' %}

{% block title %}
患者用药详情页面
{% endblock %}

{% block content %}
    <h2>患者用药详情页面</h2>
    <p>
        <a class="btn" href="{% url 'admin-detail' 'patient' patient.id %}">
            <i class="icon-arrow-left"></i>&nbsp;
            {{ patient }}</a></p>

    <div>
        {% for dosage in dosage_list %}
            <div class="well well-small">
                <p><span class="badge badge-inverse">{{ dosage.datetime|date:'Y年m月d日' }}</span></p>
                <p><span class="label label-info"><i class="icon-plus-sign"></i>&nbsp;{{ dosage.drug }}</span>
                    服药剂量：{{ dosage.dose }}
                </p>
                <p>
                    <a class="btn" href="{% url 'admin-update' 'dosage' dosage.id %}"><i class="icon-edit"></i>修改</a>
                    <a class="btn" href="{% url 'admin-delete' 'dosage' dosage.id %}"><i class="icon-remove"></i>删除</a>
                </p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

pahchina/apps/patient/templates/detail-patient.html
{% extends 'base-admin.html' %}

{% block title %}
患者详情页面
{% endblock %}

{% block content %}
    <h2>患者详情页面</h2>
    <p><a href="{% url 'admin-list' 'patient' %}" class="btn"><i class="icon-arrow-left"></i></a></p>
    <div class="form-actions">
        <a href="{% url 'admin-update' 'user' patient.user.id %}" class="btn">修改用户信息</a>
        <a href="{% url 'admin-update' 'patient' patient.id %}" class="btn">修改患者信息</a>
        <a href="{% url 'admin-detail-patient-dosage' patient.id %}" class="btn">患者用药记录</a>
        <a href="{% url 'admin-create-dosage' patient.id %}" class="btn">创建患者用药记录</a>
        <a href="{% url 'admin-list-record' patient.id %}" class="btn">患者病历记录</a>
        <a href="{% url 'create-record' patient.id %}" class="btn">创建患者病历</a>
        <a href="{% url 'list-doctor-record' patient.id %}" class="btn">患者就医记录</a>
        <a href="{% url 'admin-start-doctor-record' patient.id %}" class="btn">创建患者就医记录</a>
    </div>

    <table class="table table-bordered">
        {% with patient.user as object_user %}
        {% include 'includes/user-info-as-table.html' %}
        {% endwith %}
    </table>
    <p>

    </p>
    <table class="table table-bordered">
        {% include 'includes/patient-info-as-table.html' %}
    </table>

{% endblock %}

pahchina/apps/patient/templates/list-dosage.html
{% extends 'base-admin.html' %}

{% block title %}药物使用记录列表{% endblock %}

{% block content %}
    <h2>药物使用记录列表</h2>
{#    <p><a class="btn" href="{% url 'admin-create-dosage' patient.id %}"><i class="icon-plus"></i></a></p>#}
<table class="table table-hover">
<thead>
<tr>
    <th>药物</th>
    <th>患者</th>
    <th>用量</th>
    <th>时间</th>
</tr>
</thead>
    <tbody>
    {% for dosage in dosage_list %}
    <tr>
        <td><a href="">{{ dosage.drug }}</a></td>
        <td>
            <a href="{% url 'admin-detail-patient-dosage' dosage.patient.id %}">{{ dosage.patient }}</a>
        </td>
        <td>{{ dosage.dose }}</td>
        <td><span class="badge badge-info">{{ dosage.datetime }}</span></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

pahchina/apps/patient/templates/list-drug.html
{% extends 'base-admin.html' %}

{% block title %}药物列表{% endblock %}

{% block content %}
    <h2>药物列表</h2>
    <p><a class="btn" href="{% url 'admin-create-drug' %}"><i class="icon-plus"></i></a></p>
<table class="table table-hover">
<thead>
<tr>
    <th>名称</th>
    <th>描述</th>
    <th>价格</th>
    <th>操作</th>
</tr>
</thead>
    <tbody>
    {% for drug in drug_list %}
    <tr>
        <td><a href="">{{ drug.name }}</a></td>
        <td>{{ drug.description }}</td>
        <td><span class="badge badge-important">{{ drug.price }}元</span></td>
        <td>
        <a href="{% url 'admin-update-drug' drug.id %}"><i class="icon-edit"></i></a>
        <a href="{% url 'admin-delete-drug' drug.id %}"><i class="icon-remove"></i></a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

pahchina/apps/patient/templates/list-patient.html
{% extends 'base-admin.html' %}

{% block title %}管理患者{% endblock %}

{% block content %}
    <h2>管理患者</h2>
    <p><a class="btn" onclick="location.href=document.referrer;"><i class="icon-arrow-left"></i></a>
    <a href="{% url 'admin-create-user' %}" class="btn"><i class="icon-plus"></i></a></p>
<table class="table table-hover">
<thead>
<tr>
    <th>用户名</th>
    <th>姓名</th>
    <th>性别</th>
    <th>居住地</th>
    <th>操作</th>
</tr>
</thead>
    <tbody>
    {% for patient in patient_list %}
    <tr>
        <td><a href="{{ patient.get_url }}">{{ patient.user.username }}</a></td>
        <td>{{ patient.user.get_full_name }}</td>
        <td>{{ patient.get_sex }}</td>
        <td>{{ patient.local }}</td>
        <td>
        <a href="{% url 'admin-detail-patient' patient.id %}"><i class="icon-edit"></i></a>
        <a href="{% url 'admin-delete-user' patient.user.id %}"><i class="icon-remove"></i></a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

pahchina/apps/patient/templates/profile-patient.html
{% extends 'index-with-menu.html' %}

{% block title %}个人主页{% endblock %}
{% block h3title %}我的个人主页{% endblock %}

{% block side-content %}

        <table class="table table-bordered">

            {% with user as object_user %}
            {% include 'includes/user-info-as-table.html' %}
            {% endwith %}
            {% include 'includes/patient-info-as-table.html' %}
        </table>

{% endblock %}

pahchina/apps/patient/templates/show-patient.html
{% extends 'base-index.html' %}

{% block title %}{{ patient.user.get_identity }}{{ patient.user.username }}的个人页面{% endblock %}

{% block content %}

    <h3>{{ patient.user.get_identity }}{{ patient.user.username }}的个人页面</h3>
    <table class="table table-bordered">

        <tr>
            <th>头像</th>
            <td>
                {% if patient.user.avatar %}
                    <img src="{{ patient.user.avatar.url }}" alt=""/>
                {% endif %}
            </td>
        </tr>

        {% include 'includes/patient-info-as-table.html' %}

    </table>

{% endblock %}

pahchina/apps/patient/templates/update-patient.html
{% extends 'base-admin.html' %}

{% block title %}添加or编辑{% endblock %}

{% block head %}
    <style>
    input[type="password"] {
        background: #fff;
        border: 1px solid #ccc;
        box-shadow: 0 1px 1px #ccc inset;
        font-size: 14px;
        line-height: 20px;
        outline: medium none;
        padding: 4px 9px;
        margin: 1px;
    }
    .helptext {
        font-style: italic;
    }
    .errorlist {
        list-style: none;
        color: #b61318;
        font-weight: bold;
    }
  form li {
      list-style: none;
  }
    </style>
{% endblock %}

{% block content %}

<p><a class="btn" onclick="location.href=document.referrer;"><i class="icon-arrow-left"></i></a></p>

{#<div class="hero-unit">#}

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

<table class="table table-bordered">
    {{ form.as_table }}
</table>
    <a class="btn" onclick="location.href=document.referrer;">返回</a>
    <input class="btn btn-primary" type="submit" value="提交"/>
</form>

{#</div>#}
{% endblock %}

pahchina/apps/patient/templates/update-user-profile.html
{% extends 'index-with-menu.html' %}
{% load bootstrap_tags %}

{% block title %}修改{% endblock %}
{% block h3title %}修改{% endblock %}

{% block side-content %}


<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

    {{ form|as_bootstrap }}

    <div class="form-actions">
        <a class="btn" onclick="location.href=document.referrer;">返回</a>
        <input class="btn btn-primary" type="submit" value="提交"/>
    </div>

</form>


{% endblock %}